### ISSUE TITLE
Corrupted movie files

### ISSUE THREAD

**Issue by gsarma** [openworm/OpenWorm#280] opened 2018-04-25 17:49 UTC
**Expected behavior**
mp4 files with output of body movement simulation

**Actual behavior**
Files are generated, but they appear to be corrupted.  Error message: "The file may be damaged or may not be a movie file that is compatible with QuickTime Player."

**Steps to reproduce the behavior**
Machine Info:
MacBook Pro 2014 OS X 10.11.16
Python 2.7.11 w/ Anaconda
Docker Version 18.03.0-ce-mac60 (23751)
Xquartz 2.7.10beta2
OpenWorm Docker image from 4/23/2018

**Comment by ThatMelon** [comment] 2019-01-17 21:08
I know the cause of this, but not the solution. The error comes from the fail of the 'ffmpeg' command. Normally, running this command would work, but the command is being used in a 'check_output' command which does not allow whitespacing.

**Comment by ThatMelon** [comment] 2019-01-18 17:29
Sorry, if you would like a fix for this (and see if a fix for #291 comes out soon) you need to change line 204-205  from:

command = "ffmpeg -i %s/%s -vf blackdetect=d=0:pic_th=0.70:pix_th=0.10 -an -f null - 2>&1 | grep blackdetect" % (new_sim_out, sibernetic_movie_name)
outstr = check_output(command, shell=True
to:

outstr = check_output(["ffmpeg", "-i", "%s/%s", "-vf", "blackdetect=d=0:pic_th=0.70:pix_th=0.10", "-an", "-f", "null", "-", "2>&1", "|", "grep", "blackdetect", "%", "(new_sim_out, sibernetic_movie_name)"], shell=True)

**Comment by mwatts15** [comment] 2019-01-19 01:21
@ThatMelon You have changed the meaning of the command with your change -- there is a string format that you have removed and added the string format syntax to the ffmpeg command line.

**Comment by ThatMelon** [comment] 2019-01-19 09:37
Yeah, I thought something like this would happen. I did say on #291 that I definitely fixed it badly.

**Comment by ThatMelon** [comment] 2019-01-19 10:03
How can I fix it then?

**Comment by ThatMelon** [comment] 2019-01-19 10:47
Thanks!

**Comment by ThatMelon** [comment] 2019-01-19 10:51
So I change line 655-662? That fixes the bug?

**Comment by ThatMelon** [comment] 2019-01-19 10:55
But where is the owHelper.cpp in openworm instead of sibernetic?

**Comment by ThatMelon** [comment] 2019-01-19 13:03
Sorry, I should have tagged you @lungd. How would I go about doing the above?

**Comment by lungd** [comment] 2019-01-19 14:47
@ThatMelon you could try the following:

checkout development branch, rebuild the container, and enter the container without running the master_openworm script
```
OpenWorm$ git checkout development
OpenWorm$ ./build.sh
OpenWorm$ ./run-shell-only.sh
```

modify owHelper from inside the container:
```
ow@8b93ae070316:~$ cd sibernetic
ow@8b93ae070316:~/sibernetic$ nano src/owHelper.cpp
```
change line 656 `// membranesFile >> m_count;` to `membranesFile >> m_count;` and save it

rebuild Sibernetic and run master_openworm.py
```
ow@8b93ae070316:~/sibernetic$ make clean && make all
ow@8b93ae070316:~/sibernetic$ cd ..
ow@8b93ae070316:~$ python master_openworm.py
```

**Comment by ThatMelon** [comment] 2019-01-19 14:52
Thanks so much. You're a lifesaver

**Comment by ThatMelon** [comment] 2019-01-19 16:52
Sorry @lungd, I feel like I'm bothering you so much, unfortunately I still get "ffmpeg returned non-zero exit status 1" from the black screen detect on master_openworm.py.

**Comment by ThatMelon** [comment] 2019-01-19 16:54
This is because I get:

could not find simulation output file "/home/ow/sibernetic/NeuroML2/results/c302_C2_FW.dat"

**Comment by ThatMelon** [comment] 2019-01-19 17:10
Right, I'm confused. I ran it again and got 'output file is empty. Nothing was encoded.'

**Comment by ThatMelon** [comment] 2019-01-19 17:11
It stil says:

could not find simulation output file "/home/ow/sibernetic/NeuroML2/results/c302_C2_FW.dat"

before that though.

**Comment by ThatMelon** [comment] 2019-01-19 17:12
But I didn't get the ffmpeg error.

**Comment by ThatMelon** [comment] 2019-01-19 21:52
I'm sorry @lungd, I don't know how to make this not seem mean but do you have any idea why I get no output. I must seem really pushy, mustn't I?

**Comment by slarson** [comment] 2019-01-21 19:52
@ThatMelon Best thing would be if you can commit your version as a fork to your own repo and share on the issue so others can try what you've done.  There's virtually no way to answer your question without your version of the running code loaded locally.

**Comment by ThatMelon** [comment] 2019-01-21 20:32
Also, I had to complete the steps @lungd provided so I didn't get an FFmpeg error due to sibernetic crashing.

**Comment by ThatMelon** [comment] 2019-01-21 21:08
Oh, I'm really sorry I forgot to link you the fork. It's at thatmelon/Openworm

**Comment by slarson** [comment] 2019-01-22 15:32
@ThatMelon Thanks!  Link to the relevant branch?

**Comment by ThatMelon** [comment] 2019-01-27 11:56
@slarson Is there any progress?

**Comment by lungd** [comment] 2019-01-28 15:10
@ThatMelon sorry for the delay.
I pushed the fix I mentioned above (and some other mostly minor modifications) to my own repo: https://github.com/lungd/OpenWorm/tree/development
I tested the container and it worked on my system.

Your issue could also be related to the setup of your system.
I think the simulation needs to allocate more than 4GB, thus, a system with only 4GB of RAM and without swap space could also explain such a behavior.

**Comment by ThatMelon** [comment] 2019-01-28 17:07
Thanks! I shall try this now.

**Comment by ThatMelon** [comment] 2019-01-28 17:34
The tag is not on docker hub.

**Comment by lungd** [comment] 2019-01-28 17:40
I think you forgot to run `./build.sh`.

BTW, I only tested my repo with `./run-shell-only.sh` and then calling `python master_openworm.py`

**Comment by ThatMelon** [comment] 2019-01-28 17:41
Ahh. I'm obviously not good at this.

**Comment by ThatMelon** [comment] 2019-01-28 18:07
I still get the output file is empty error.

**Comment by lungd** [comment] 2019-01-28 18:18
Can you please share the entire output of the master_openworm script? (www.pastebin.com)

**Comment by ThatMelon** [comment] 2019-01-28 18:19
Sure!

**Comment by ThatMelon** [comment] 2019-01-28 18:19
I'll send you a link soon.

**Comment by lungd** [comment] 2019-01-28 19:10
You could also monitor memory usage with, e.g., `htop` (mby you need to install it first) of your VM.
Start htop inside a new terminal and check whether your VM runs out of memory (incl swap if available) during the simulation.

**Comment by ThatMelon** [comment] 2019-01-28 19:10
@lungd. It passes the 512KB limit.

**Comment by ThatMelon** [comment] 2019-01-28 19:18
I have found an alternative. Here you go @lungd!

https://www.pastefs.com/pid/98591

**Comment by lungd** [comment] 2019-01-29 15:12
I wanted to know the vendor/brand of your CPU.
Is it an Intel or AMD CPU?

**Comment by lungd** [comment] 2019-01-29 15:58
@ThatMelon please post the output of `grep flags /proc/cpuinfo | uniq | grep -oP 'sse([^\s]+)*'`

**Comment by larson** [comment] 2019-01-29 16:11
@ThatMelon I got tagged in this in "how can I install an AMD CPU on my VM" but I think you meant @slarson .

**Comment by lungd** [comment] 2019-01-29 16:16
@larson you are right. Seems to be a typo.

**Comment by ThatMelon** [comment] 2019-01-29 16:33
Sorry yes. I was wrong. I meant to type lungd then accidently thought in my head slarson and then wrote larson by mistake. Sorry!

**Comment by ThatMelon** [comment] 2019-01-29 16:49
@lungd the output of the cpuinfo command is:

sse
sse2
sse3
sse4_1
sse4_2
sse4a
sse

**Comment by lungd** [comment] 2019-01-29 16:55
@ThatMelon Intel or AMD CPU?
output of `lscpu | grep Vendor` ?

**Comment by ThatMelon** [comment] 2019-01-29 18:36
I'll open a new issue.

**Comment by pgleeson** [comment] 2019-01-30 11:59
@lungd I've managed to run the Docker container in your development branch and it generated the movies fine. 

Do you want to open some of your sibernetic PRs on my https://github.com/pgleeson/sibernetic/tree/development branch and I'll test them, as there's already a PR open for this to the main sibernetic repo (though you don't seem to have all the changes from that on your branches)?

**Closed as completed** 2019-01-30 13:35 UTC
